//
// Created by jason on 10.03.22.
//

#ifndef TRAFFICSIMULATION2022_STANDARD_VALUES_H
#define TRAFFICSIMULATION2022_STANDARD_VALUES_H


class Standard_Values {

};


#endif //TRAFFICSIMULATION2022_STANDARD_VALUES_H
