//
// Created by jason on 03.03.22.
//

#ifndef TRAFFICSIMULATION2022_TRAFFICSIMULATIONREADER_H
#define TRAFFICSIMULATION2022_TRAFFICSIMULATIONREADER_H


class TrafficSimulationReader {

};


#endif //TRAFFICSIMULATION2022_TRAFFICSIMULATIONREADER_H
