//
// Created by jason on 15/03/2022.
//

#ifndef TRAFFICSIMULATION2022_TRAFFICLIGHTTEST_H
#define TRAFFICSIMULATION2022_TRAFFICLIGHTTEST_H


class TrafficLightTest {

};


#endif //TRAFFICSIMULATION2022_TRAFFICLIGHTTEST_H
